# Generated by Django 5.1.3 on 2024-11-30 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlists', '0004_waitlistentry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitlistentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
